all:
  children:

    bastion:
      hosts:
        projet-ops-bastion:
          ansible_connection: docker
          ansible_user: root
          ansible_remote_tmp: /tmp/.ansible/tmp
          ansible_python_interpreter: /usr/bin/python3

    loadbalancer:
      hosts:
        projet-ops-haproxy:
          ansible_connection: docker
          ansible_user: root
          ansible_remote_tmp: /tmp/.ansible/tmp
          ansible_python_interpreter: /usr/bin/python3.13

    webservers:
      hosts:
        projet-ops-web1:
          ansible_connection: docker
          ansible_user: root
          ansible_remote_tmp: /tmp/.ansible/tmp
          ansible_python_interpreter: /usr/bin/python3.13
          server_id: "web1"
        projet-ops-web2:
          ansible_connection: docker
          ansible_user: root
          ansible_remote_tmp: /tmp/.ansible/tmp
          ansible_python_interpreter: /usr/bin/python3.13
          server_id: "web2"

    database:
      hosts:
        projet-ops-postgres:
          ansible_connection: docker
          ansible_user: root
          ansible_remote_tmp: /tmp/.ansible/tmp
          ansible_python_interpreter: /usr/bin/python3